language: scala
jdk:
- oraclejdk8
scala:
- 2.12.6
script:
- sbt ++$TRAVIS_SCALA_VERSION test packageBin packageDoc packageSrc packagedArtifacts
sudo: false
notifications:
  email:
  - sergei@digital-magic.io
deploy:
  provider: bintray
  file: ".bintray.json"
  user: LoneEngineer
  key:
    secure: k+nypOceDIk5dHonZ7oBBujTFQIH42zBk1yeGPULq1VcUFBAEJ9KbGIchur+hv8gb1uUrZ1hw29nEMCR654ZNZNKxb+Qqt+0Fis7jhSJgGgsUv2JmF4Ync9DV4cgzd6578icTR8qPgGYU8Twpit8dz/qi8r5vAGFBglguCmlyXqxoKVl5AB3NLTAz/yn58BQvIT+8LaVVzsJqvUrEVp+mQXy0qp2RXRmKtqOkEGUe8AYBtzN6LWKfvbi8S1qat1GuDk34pYCU1yfrkKF76El+LQKoMAnNJ8dBapshT7uc0MNDvTt29/f9HVbWmzElbG/gNc2AHH1SmCSTlhE3iFUQGFVbM1dR3tpLeIMMJfFulkwKNKLXxuttu6IlGBZuTkKCMdaKJ4B78ecWE80WkFZjcV1EVQ29q/Vh15VOWpzjt7hMoPzBVW1t77JJS/Ky6R4i/e46UT0TPR+eLX89FBcFink2jwz3Gyh7NY+FAg4nFYPF4iGRwBBr5rO57b068GRkeRHquo+vkJwbR6edFk9pkOVuBWtJuxOfCHM8ND74LsKE82GwYdr3CZsfrlKPKPuo/1/lxHaxZ5p7l2jWq4qzfNCttdYx2sqmqThhm4O1xefSVzdOY8AcgniyUzzWfW8RwB7EgYpbyOr9pcHsQCo1BcqTlu5mEry090/OvFt2+c=
  on: 2.5.0.0
  skip_cleanup: true
